---
- name: Install Firefox
  become: true
  become_user: root
  community.general.pacman:
    name: firefox
    state: present

- name: Install speech-dispatcher
  become: true
  become_user: root
  community.general.pacman:
    name: speech-dispatcher
    state: present
  register: speech_dispatched

- name: Install sound-icons
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name: sound-icons
    use: yay
    state: present
  when: speech_dispatched
