---
- name: Install gamemode
  become: true
  become_user: root
  community.general.pacman:
    name:
      - gamemode
    state: present

- name: Register gamemode user
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    groups: gamemode
    append: yes

