---
- name: Install gamemode
  become: true
  become_user: root
  community.general.pacman:
    name:
      - gamemode
    state: present

- name: Register gamemode user
  become: true
  become_user: root
  user:
    name: "{{ user.name }}"
    groups: gamemode
    append: yes

- name: Copy global gamemode config
  become: true
  become_user: "root"
  ansible.builtin.copy:
    src: gamemode.ini
    dest: /etc/gamemode.ini
    mode: "0644"
