---
# Grab CPU flags from `/proc/cpuinfo` and put the result into the
# `cpu_flags_cmd` variable.
- name: Get cpu flags
  ansible.builtin.command: >
    awk -F: '/^flags/ {print $2; exit}' /proc/cpuinfo
  register: cpu_flags_cmd

# Extract the flags into a list variable named `cpu_flags`.
- name: Set cpu flags fact
  ansible.builtin.set_fact:
    cpu_flags: "{{ cpu_flags_cmd.stdout.split() }}"

# Identify the processor manufacturer by looking for "Intel" or "AMD"
# in `/proc/cpuinfo`.
- name: Check if Intel processor
  ansible.builtin.command: grep -q Intel /proc/cpuinfo
  ignore_errors: true
  register: is_intel

- name: Check if AMD processor
  ansible.builtin.command: grep -q AMD /proc/cpuinfo
  ignore_errors: true
  register: is_amd

- name: Install microcode updates for intel (if necessary)
  become: true
  become_user: root
  community.general.pacman:
    name: intel-ucode
    state: present
  when: is_intel

- name: Install microcode updates for amd (if necessary)
  become: true
  become_user: root
  community.general.pacman:
    name: amd-ucode
    state: present
  when: is_amd
