- name: Install printing tools
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - cups
    - cups-browsed
    - cups-pk-helper
  register: cups_installed

- name: Enable and start cups service
  become: true
  become_user: root
  ansible.builtin.service:
    name: cups
    state: started
    enabled: true
  when: cups_installed

- name: Enable cups-browsed
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: cups-browsed
    enabled: true
    state: started
