---
- name: Install Hyprland
  become: true
  become_user: root
  community.general.pacman:
    name:
      - aquamarine
      - hyprcursor
      - xdg-desktop-portal-hyprland
      - hyprpaper
      - hypridle
      - hypridle
      - hyprlock
      - hyprwayland-scanner
      - hyprsunset
      - hyprpolkitagent
      - hyprutils
      - hyprpicker
      - hyprlang
      - hyprland
    state: present
  when: not use_hyprland_git

- name: Install Hyprland-git
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - hyprland-meta-git
    use: yay
    state: present
  when: use_hyprland_git

- name: Install gtk and kde portals
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - xdg-desktop-portal-gtk
      #      - xdg-desktop-portal-kde
    use: yay
    state: present

- name: Create ~/.config/xdg-desktop-portal/ directory
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.file:
    path: ~/.config/xdg-desktop-portal/
    state: directory
    mode: "0755"
  register: xdg_portald

- name: Configure automatic D-Bus activation
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.blockinfile:
    path: ~/.config/xdg-desktop-portal/hyprland-portals.conf
    append_newline: true
    create: true
    block: |
      [preferred]
      default=hyprland;gtk
      org.freedesktop.impl.portal.Settings=darkman
    mode: "0644"
  when: xdg_portald

- name: Install hyprcursor themes
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - aur/bibata-cursor-git
    use: yay
    state: present

- name: Install pyprland
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - aur/pyprland
    use: yay
    state: present
#- name: Add Hyprland official plugins
#  become: true
#  become_user: "{{ user.name }}"
#  ansible.builtin.command: "hyprpm add https://github.com/hyprwm/hyprland-plugins"
#register: hyprland_official_plugins_installed
#ignore_errors: true

#- name: Add shezdy/hyprsplit plugin
#  become: true
#  become_user: "{{ user.name }}"
#  ansible.builtin.command: "hyprpm add https://github.com/shezdy/hyprsplit"
#  register: hyprsplit_installed
#  ignore_errors: true

#- name: Add KZDKM/Hyprspace plugin
#  become: true
#  become_user: "{{ user.name }}"
#  ansible.builtin.command: "hyprpm add https://github.com/KZDKM/Hyprspace"
#  register: hyprspace_installed
#  ignore_errors: true

#- name: Enable hyprexpo plugin
#become: true
#become_user: "{{ user.name }}"
#ansible.builtin.command: "hyprpm enable hyprexpo"
#when: hyprland_official_plugins_installed
#notify: Run hyprpm update
#ignore_errors: true

# - name: Enable hyprbars plugin
#   become: true
#   become_user: '{{ user.name }}'
#   ansible.builtin.command: 'hyprpm enable hyprbars'
#   when: hyprland_official_plugins_installed
#   notify: Run hyprpm update
#   ignore_errors: yes

#- name: Enable hyprsplit plugin
#become: true
#become_user: "{{ user.name }}"
#ansible.builtin.command: "hyprpm enable hyprsplit"
#when: hyprsplit_installed
#notify: Run hyprpm update
#ignore_errors: true
