---
- name: Sanity check hostname
  when: not system.hostname
  ansible.builtin.fail:
    msg: "Hostname has not been set."

- name: Create hostname file
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/hostname
    line: "{{ system.hostname }}"
    create: true
    mode: "0644"

- name: Update /etc/hosts
  become: true
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/hosts
    append_newline: true
    create: true
    block: |
      {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ system.hostname }} {{ system.hostname.split('.')[0] }}
    mode: "0644"
