---
- name: Gather facts
  hosts: all
  tags:
    - always

- name: Core
  ansible.builtin.import_playbook: playbooks/core.yaml

- name: CLI
  ansible.builtin.import_playbook: playbooks/cli.yaml

- name: Hyprland
  ansible.builtin.import_playbook: playbooks/gui_hyprland.yaml

- name: KDE
  ansible.builtin.import_playbook: playbooks/gui_kde.yaml

- name: KDE_PIM
  ansible.builtin.import_playbook: playbooks/kde_pim.yaml

- name: COSMIC
  ansible.builtin.import_playbook: playbooks/gui_cosmic.yaml

- name: Gnome
  ansible.builtin.import_playbook: playbooks/gui_gnome.yaml

- name: Games
  ansible.builtin.import_playbook: playbooks/games.yaml

- name: Users
  ansible.builtin.import_playbook: playbooks/users.yaml
  when: user.name

- name: Virtualization
  ansible.builtin.import_playbook: playbooks/virtualization.yaml
  when: install_virtualization

- name: Development GUI tools
  ansible.builtin.import_playbook: playbooks/dev_gui.yaml

- name: Firewall
  ansible.builtin.import_playbook: playbooks/firewall.yaml

- name: Fonts
  ansible.builtin.import_playbook: playbooks/fonts.yaml
