---
- name: Gather facts
  hosts: all
  tags:
    - always

- name: Core
  ansible.builtin.import_playbook: playbooks/core.yaml

- name: CLI
  ansible.builtin.import_playbook: playbooks/cli.yaml

- name: Hyprland
  ansible.builtin.import_playbook: playbooks/gui_hyprland.yaml

- name: KDE
  ansible.builtin.import_playbook: playbooks/gui_kde.yaml

- name: COSMIC
  ansible.builtin.import_playbook: playbooks/gui_cosmic.yaml

- name: Games
  ansible.builtin.import_playbook: playbooks/games.yaml

- name: Users
  ansible.builtin.import_playbook: playbooks/users.yaml
  when: user.name

- name: Virtualization
  ansible.builtin.import_playbook: playbooks/virtualization.yaml
  when: install_virtualization
