---
- name: Install Zotero
  become: true
  become_user: '{{ aur_builder_user }}'
  kewlfft.aur.aur:
      name:
          - zotero-bin
      use: yay
      state: present

- name: Install Zotero profile-sync-daemon profile
  become: true
  become_user: '{{ aur_builder_user }}'
  kewlfft.aur.aur:
      name:
          - profile-sync-daemon-zotero
      use: yay
      state: present
