---
- name: Install Cosmic Desktop
  become: true
  become_user: root
  community.general.pacman:
    name:
      - cosmic
      - cosmic-player
    state: present

- name: Install XDG portals
  become: true
  become_user: root
  community.general.pacman:
    name:
      - xdg-desktop-portal-cosmic
    state: present

- name: Enable cosmic greeter
  become: true
  become_user: root
  ansible.builtin.service:
    name: cosmic-greeter
    enabled: true
