---
- name: Install Cosmic Desktop
  become: true
  become_user: root
  community.general.pacman:
    name:
      - cosmic-notifications
      - cosmic-text-editor
      - cosmic-wallpapers
      - cosmic-screenshot
      - cosmic-settings-daemon
      - cosmic-launcher
      - cosmic-settings
      - cosmic-applets
      - cosmic-session
      - cosmic-app-library
      - cosmic-workspaces
      - cosmic-files
      - cosmic-randr
      - cosmic-terminal
      - cosmic-panel
      - cosmic-greeter
      - cosmic-comp
      - cosmic-store
      - cosmic-idle
      - cosmic-osd
      - cosmic-bg
    state: present

- name: Install XDG portals
  become: true
  become_user: root
  community.general.pacman:
    name:
      - xdg-desktop-portal-cosmic
    state: present

- name: Enable cosmic greeter
  become: true
  become_user: root
  ansible.builtin.service:
    name: cosmic-greeter
    enabled: true
