- name: Install TeXLive
  become: true
  become_user: root
  community.general.pacman:
    name: texlive
    state: present

- name: Install additional TeX packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - biber
      - dialog
      - ed
      - luametatex
      - perl-file-homedir
      - perl-ipc-system-simple
      - perl-tk
      - perl-yaml-tiny
      - python
      - python-pygments
      - texlive-fontsextra
      - texlive-fontsrecommended
      - texlive-lang
      - texlive-latexextra
      - texlive-latexrecommended
      - wdiff
