---
- name: Install TeXLive
  become: true
  become_user: root
  kewlfft.aur.aur:
    name: texlive-installer
    state: present

- name: display post install message
  debug: msg="Run sudo `/opt/texlive-installer/install-tl` to install TexLive"

- name: Install additional TeX packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - biber
    - dialog
    - ed
    - luametatex
    - perl-file-homedir
    - perl-ipc-system-simple
    - perl-tk
    - perl-yaml-tiny
    - python
    - python-pygments
    - wdiff
