---
- name: Install OpenSSH
  become: true
  become_user: root
  community.general.pacman:
    name: openssh
    state: present

- name: Copy sshd conf files
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssh/sshd_config.d/{{ item }}"
    mode: 0644
  register: sshd_conf
  when: "item != ''"
  loop:
    - 01-basic-sshd-hardening.conf
    - "{{ '02-sshd-x11forwarding.conf' if vars.openssh.xforwarding else '' }}"
    - 03-sshd-gpg-agent.conf

- name: Enable ssh server
  ansible.builtin.service:
    name: sshd
    enabled: true
  when: openssh.enable

- name: Enable ssh server
  ansible.builtin.service:
    name: sshd
    state: started
  when: openssh.start
