---
- name: Install nautilus
  become: true
  become_user: root
  community.general.pacman:
    name:
      - nautilus
      - nautilus-share
      - nautilus-python
      - nautilus-image-converter
      - libnautilus-extension
      - libnautilus-extension-docs
      - nautilus-image-converter
    state: present
  notify: Set Nautilus as default file manager

- name: Install Nautilus addons
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - nautilus-admin-gtk4
      - nautilus-open-any-terminal
      - seahorse-nautilus
      - nautilus-metadata-editor
      - nautilus-checksums
      - nautilus-hide
      - nautilus-image-converter
      - nautilus-annotations
    use: yay
    state: present

- name: Install Thumbnailers for Nautilus
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - ffmpegthumbnailer
      - gst-libav
      - ffmpeg-audio-thumbnailer
      - webp-pixbuf-loader
      - freetype2
      - libgsf
      - raw-thumbnailer
      - totem
      - evince
    use: yay
    state: present
