---
- name: Install kvantum
  become: true
  become_user: root
  community.general.pacman:
    name:
      - kvantum
    state: present

- name: Install qt6-svg
  become: true
  become_user: root
  community.general.pacman:
    name:
      - qt6-svg
    state: present

- name: Install qalculate-gtk
  become: true
  become_user: root
  community.general.pacman:
    name:
      - qalculate-gtk
    state: present
