---
- name: Deploy Hyprland wayland override config
  ansible.builtin.copy:
    src: 10-wayland.conf
    dest: /etc/sddm.conf.d/10-wayland.conf
    mode: "0644"

- name: Deploy SDDM theme config
  ansible.builtin.copy:
    src: 20-theme.conf
    dest: /etc/sddm.conf.d/20-theme.conf
    mode: "0644"

- name: Deploy Hyprland compositor config
  ansible.builtin.copy:
    src: hyprland.conf
    dest: /etc/sddm.conf.d/hyprland.conf
    mode: "0644"
