---
- name: Install Avahi mDNS
  become: true
  become_user: root
  community.general.pacman:
    name: avahi
    state: present
  register: avahi_installed

- name: Install nss-mdns
  become: true
  become_user: root
  community.general.pacman:
    name: nss-mdns
    state: present

- name: Deploy disable_mdns
  become: true
  become_user: root
  ansible.builtin.copy:
    src: 1-disable_mdns.conf
    dest: /etc/systemd/resolved.conf.d/
    mode: "0644"
  notify:
    - Restart resolved
  register: no_resolvedmdns

- name: Start Avahi Daemon
  become: true
  become_user: root
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: true
  when:
    - avahi_installed
    - no_resolvedmdns

- name: Add nss-mdns entries
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/nsswitch.conf
    state: "present"
    # Whitespace to keep nice formatting within the file
    line: "hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns"
    regexp: "^hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns$"
