---
- name: Install rEFInd bootloader and tools
  become: true
  become_user: root
  community.general.pacman:
    name: refind
    state: present
  register: installed_refind

- name: Install refind to boot partition
  become: true
  become_user: root
  # We can't do this as a handler,
  # as the following tasks rely on files created in this step
  when: installed_refind.changed  # noqa: no-handler
  changed_when: true
  ansible.builtin.command:
    cmd: refind-install --yes

- name: Find UEFI partition
  ansible.builtin.shell: 'cat /etc/fstab |grep efi | grep UUID | cut -f 2'
  register: uefi_path

- name: Teach refind about Arch kernel version strings
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: "{{ uefi_path.stdout | replace(' ', '') }}/EFI/refind/refind.conf"
    line: 'extra_kernel_version_strings linux-hardened,linux-rt-lts,linux-zen,linux-lts,linux-rt,linux'
    regexp: '^extra_kernel_version_strings '
    insertafter: '^#extra_kernel_version_strings'

- name: Get boot device UUID
  ansible.builtin.command: "blkid -s UUID -o value {{ root_device }}"
  register: refind_root_uuid

- name: Get swap device UUID
  ansible.builtin.shell: 'cat /etc/fstab | grep swap | grep UUID | cut -f 1'
  register: refind_swap_uuid

- name: Generate boot additional parameters
  ansible.builtin.set_fact:
    boot_additional_parameters: "{{ common_boot | join(' ') }}"

- name: Generate AMD boot additional parameters for AMD graphics
  ansible.builtin.set_fact:
    amd_additional_params: "{{ common_boot + amd_boot }}"
  when: system.graphics_card == "amd"
  register: combined_common_and_amd

- name: Combine AMD boot parameters
  ansible.builtin.set_fact:
    boot_additional_parameters: "{{ amd_additional_params | join(' ') }}"
  when: combined_common_and_amd

- name: Populate kernel command line root file
  become: true
  become_user: root
  ansible.builtin.template:
    src: refind_linux.conf.j2
    dest: /boot/refind_linux.conf
    mode: '0644'
  when:
    - refind_root_uuid
    - refind_swap_uuid

- name: Create /etc/pacman.d/hooks/ directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: '0755'
  register: created_pacmand_hooks_dir

- name: Deploy refind hook
  become: true
  become_user: root
  ansible.builtin.copy:
    src: refind.hook
    dest: /etc/pacman.d/hooks/
    mode: '0644'
  when: created_pacmand_hooks_dir

- name: Change timeout to 3 seconds
  ansible.builtin.lineinfile:
    path: /efi/EFI/refind/refind.conf
    regexp: '^timeout 20'
    line: 'timeout 3'
