- name: Install Spotify
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - spotify
      - zenity
      - ffmpeg4.4
      - spotifywm-git
    use: yay
    state: present
