- name: Install makepkg dropin packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ccache
    - pbzip2
    - pigz

- name: Deploy makepkg dropin for build environments
  become: true
  become_user: root
  ansible.builtin.copy:
    src: mkpkg-buildenv.conf
    dest: /etc/makepkg.conf.d/
    mode: '0644'

- name: Deploy makepkg dropin for compiler settings
  become: true
  become_user: root
  ansible.builtin.copy:
    src: mkpkg-compiler.conf
    dest: /etc/makepkg.conf.d/
    mode: '0644'

- name: Deploy makepkg dropin for compression
  become: true
  become_user: root
  ansible.builtin.copy:
    src: mkpkg-compression.conf
    dest: /etc/makepkg.conf.d/
    mode: '0644'

- name: Deploy makepkg dropin for global options
  become: true
  become_user: root
  ansible.builtin.copy:
    src: mkpkg-global-options.conf
    dest: /etc/makepkg.conf.d/
    mode: '0644'
