---
- name: Install firewalld
  become: true
  become_user: root
  community.general.pacman:
    name: firewalld
    state: present

- name: Enable and start FirewallD
  become: true
  become_user: root
  ansible.builtin.service:
    name: firewalld.service
    enabled: true
    state: started

- name: Remove interfaces from "Public" (permanent)
  become: true
  become_user: root
  ansible.posix.firewalld:
    zone: public
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  with_items:
    - "{{ ansible_interfaces }}"
  when: ('item.startswith("wl")' or 'item.startswith("enp")')
  notify: Restart FirewallD
  register: removed_public

- name: Change network for interfaces to "Home" (permanent)
  become: true
  become_user: root
  ansible.posix.firewalld:
    zone: home
    interface: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "{{ ansible_interfaces }}"
  when:
    - ('item.startswith("wl")' or 'item.startswith("enp")')
    - removed_public
  notify: Restart FirewallD

- name: Updating home zone rules
  become: true
  become_user: root
  ansible.posix.firewalld:
    zone: home
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - ssh
    - mdns
    - samba-client
    - dhcpv6-client
    - cockpit
    - ipsec
    - syncthing
    - syncthing-gui
    - syncthing-relay
    - upnp-client
    - mndp

- name: Use nmcli to set firewalld zone
  become: true
  become_user: root
  community.general.nmcli:
    type: ethernet
    conn_name: 'Wired connection 1'
    zone: home
    state: present
