---
- name: Install Gnome
  become: true
  become_user: root
  community.general.pacman:
    name:
      - gnome
      - gnome-extra
    state: present
  when: not use_hyprland_git

- name: Enable gdm greeter
  become: true
  become_user: root
  ansible.builtin.service:
    name: gdm
    enabled: true
