---
- name: Install Zen browser
  become: true
  become_user: '{{ aur_builder_user }}'
  kewlfft.aur.aur:
      name:
          - zen-browser-avx2-bin
      use: yay
      state: present

- name: Install Zen profile-sync-daemon profile
  become: true
  become_user: '{{ aur_builder_user }}'
  kewlfft.aur.aur:
      name:
          - profile-sync-daemon-zen
      use: yay
      state: present
