---
refind_common_boot:
  - zswap.enabled=0
  - nowatchdog
  - splash

refind_amd_boot:
  - amd_pstate=active
  - amdgpu.dc=1

refind_root_device: "{{ ansible_mounts | json_query('[?mount == `/`].device') | first }}"
