---
- name: Install Yubikey Items
  become: true
  become_user: root
  community.general.pacman:
    name:
      - yubikey-touch-detector
      - yubikey-manager
      - yubico-pam
      - yubikey-manager-qt
      - yubikey-personalization
      - yubikey-personalization-gui
      - yubico-piv-tool
      - age-plugin-yubikey
    state: present

- name: Start yubikey-touch-detector
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.service:
    name: yubikey-touch-detector.service
    scope: user
    state: started
    enabled: true
  when:
    - user.name != "root"
    - user.name != "aur_builder"
