---
mkinitcpio_initrd_mods: "crc32c btrfs usbhid xhci_hcd"
mkinitcpio_initrd_bin: "/usr/bin/btrfs"
mkinitcpio_initrd_files: ""
mkinitcpio_initrd_hooks_pre: "base systemd keyboard"
mkinitcpio_initrd_hooks_post: "autodetect modconf microcode kms sd-vconsole sd-encrypt block filesystems fsck resume"
mkinitcpio_initrd_compression: "zstd"
mkinitcpio_initrd_compression_options: "-c -T{{ ansible_processor_nproc }} -"
mkinitcpio_root_device: "{{ ansible_mounts | json_query('[?mount == `/`].device') | first }}"
