---
- name: Install imagemagick
  become: true
  become_user: root
  community.general.pacman:
    name: imagemagick
    state: present

- name: Install image format libraries
  become: true
  become_user: root
  community.general.pacman:
    name:
      - ghostscript
      - jbigkit
      - libheif
      - libjpeg-turbo
      - libjxl
      - libraw
      - librsvg
      - libtiff
      - libultrahdr
      - libwebp
      - libwmf
      - libzip
      - ocl-icd
      - openexr
      - openjpeg2
      - djvulibre
      - pango
      - perl-image-exiftool
    state: present
