---
- name: Install (KDE) Partition Manager
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - partitionmanager
    - bcachefs-tools
    - dosfstools
    - e2fsprogs
    - exfatprogs
    - f2fs-tools
    - jfsutils
    - udftools
    - xfsprogs
    - ntfs-3g
