---
- name: Install neofetch
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name: neofetch
    use: yay
    state: present

- name: Install neofetch Libraries
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - chafa
      - ddcutil
      - hwdata
      - libdrm
      - libelf
      - libpulse
      - ocl-icd
      - vulkan-icd-loader
      - zlib
    use: yay
    state: present
