---
- name: Install msmtp
  become: true
  become_user: root
  community.general.pacman:
    name:
      - msmtp

- name: Check if .msmtprc exists
  become: true
  become_user: '{{ user.name }}'
  stat:
    path: ~/.msmtprc
  register: smtprc_exists

- name: Use msmtp to generate a config file
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.command: 'msmtp --configure {{ user.email }} > ~.msmtprc'
  when: not smtprc_exists
