---
- name: Install msmtp
  become: true
  become_user: root
  community.general.pacman:
    name:
      - msmtp

- name: Check if system msmtprc exists
  become: true
  become_user: root
  stat:
    path: /etc/msmtprc
  register: system_smtprc_exists

- name: Deploy system msmtprc
  become: true
  become_user: root
  ansible.builtin.template:
    src: system-msmtprc.j2
    dest: /etc/msmtprc
    mode: "0o644"
  when: not system_smtprc_exists
# - name: Check if .msmtprc exists
#   become: true
#   become_user: "{{ user.name }}"
#   stat:
#     path: ~/.msmtprc
#   register: smtprc_exists

# - name: Use msmtp to generate a config file
#   become: true
#   become_user: "{{ user.name }}"
#   ansible.builtin.command: "msmtp --configure {{ user.email }} > ~.msmtprc"
#   when: not smtprc_exists
