---
- name: Ensure the user exists -- "{{ user.name }}"
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "/usr/bin/{{ user.shell }}"
    groups:
      - users
      - wheel
      - network
      - lock
      - uucp
      - input
    append: true
    system: false
    createhome: true
    home: /home/{{ user.name }}
