---
- name: Install Arch Gaming metapackage
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - arch-gaming-meta
      - dxvk-bin
      - proton-ge-custom
      - proton-tricks
      - protonup-qt
    use: yay
    state: present
