---
- name: Install Arch Gaming metapackage
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - arch-gaming-meta
      - dxvk-bin
      - proton-ge-custom
      - proton-tricks
      - protonup-qt
    use: yay
    state: present

- name: Install additional 32-bit libraries
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - lib32-gamemode
    use: yay
    state: present

- name: Install Additional gaming-adjacent tools
  become: true
  become_user: root
  kewlfft.aur.aur:
    name:
      - lact
      - coolercontrol
      - coolercontrol-liqctld
    use: yay
    state: present

- name: Enable and start lact
  become: true
  become_user: root
  ansible.builtin.service:
    name: lactd
    enabled: true
    state: started

- name: Enable and start coolercontrold
  become: true
  become_user: root
  ansible.builtin.service:
    name: coolercontrold
    enabled: true
    state: started
