---
- name: Remove Jack
  become: true
  become_user: root
  community.general.pacman:
    name:
      - jack2
    state: absent
  ignore_errors: true

- name: Install pipewire
  become: true
  become_user: root
  community.general.pacman:
    name:
      - alsa-utils
      - pipewire
      - pipewire-audio
      - pipewire-jack
      - pipewire-pulse
      - pipewire-session-manager
      - qpwgraph
      - wireplumber
    state: present

- name: Install pavucontrol
  become: true
  become_user: root
  community.general.pacman:
    name:
      - pavucontrol
    state: present

- name: Create pipewire config directory
  ansible.builtin.file:
    path: ~/.config/wireplumber/wireplumber.conf.d
    state: directory
    mode: "0o755"
  register: created_wireplumber_conf_dir

- name: Deploy 51-disable-suspension.conf
  ansible.builtin.copy:
    src: 51-disable-suspension.conf
    dest: ~/.config/wireplumber/wireplumber.conf.d/
    mode: "0o644"
  when: created_wireplumber_conf_dir
