- name: Install core OS base packages
  become: true
  become_user: root
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - base
    - ansible
    - python-jmespath
    - bash
    - coreutils
    - curl
    - dateutils
    - git
    - fish
    - lsof
    - man-db
    - man-pages
    - neovim
    - openssh
    - strace
    - sysstat
    - texinfo
    - udisks2
    - udisks2-btrfs
    - exfatprogs
  register: minimal_packages_deployed
