---
- name: Install inkscape
  become: true
  become_user: root
  community.general.pacman:
    name:
      - inkscape
    state: present

- name: Install Inkscape dependencies
  become: true
  become_user: root
  community.general.pacman:
    name:
      - graphicsmagick
      - jasper
      - libwmf
      - ghostscript
      - libheif
      - fig2dev
      - gvfs
      - pstoedit
      - texlive-pstricks
    state: present
