---
- name: Install arch-update
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name: arch-update
    use: yay
    state: present
  notify: Run arch-update

- name: Start arch-update timer
  ansible.builtin.systemd_service:
    name: arch-update.timer
    state: started
    enabled: true
    scope: user
