---
- name: Firewall
  hosts: all
  become: true
  become_user: root
  roles:
    - { role: networkmanager, tags: ["networkmanager"] }
    - { role: firewall, tags: ["firewall"] }
  tags:
    - firewall
