---
- name: Games
  hosts: all
  become: true
  become_user: root
  roles:
    - role: arch_gaming_meta
    - { role: steam, tags: ["steam"] }
    - { role: cartridges, tags: ["cartridges"] }
  tags:
    - games
