---
- name: Install KDE Plasma Desktop
  hosts: all
  become: true
  become_user: root
  roles:
    - role: pipewire
    - role: qt6_multimedia
    - role: qt_wayland
    - role: plasma_desktop
    - role: bibata
    - role: dev_gui
  tags:
    - plasma_desktop
