---
- name: Install Virtualization Tools
  hosts: all
  become: true
  become_user: root
  roles:
    - { role: qemu, tags: ["qemu"] }
    - { role: libvirt, tags: ["libvirt"] }
  tags:
    - virtualization
