---
- name: Install 1Password
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - 1password
      - 1password-cli
    use: yay
    state: present

- name: Add custom_allowed_browsers
  become: true
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/1password/custom_allowed_browsers
    append_newline: true
    create: true
    block: |
      zen-bin
    mode: "0644"
