- name: Install Misc fonts
  become: true
  become_user: "{{ aur_builder_user }}"
  kewlfft.aur.aur:
    name:
      - awesome-terminal-fonts
      - noto-fonts-emoji
      - otf-font-awesome
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-font-icons
      - ttf-hack
      - ttf-inconsolata
      - ttf-jetbrains-mono-nerd
      - ttf-liberation
      - ttf-meslo-nerd-font-powerlevel10k
      - ttf-pragmasevka-nerd-font
    use: yay
    state: present
